### ISSUE TITLE
`bindings` vs `bindingOverrides` and `keys` vs `key` 

### ISSUE THREAD

**Issue by TwoClocks** [VSpaceCode/vscode-which-key#78]
As I've been adding more overrides, at some point I've made enough changes that I just want to skip the defaults. I'd assumed I just needed to change `bindingOverrides` to `bindings` and it would work. It doesn't.
I needed to go and change all the group bindings from `keys` to `key`.

It would be nice to just be able to flip back and forth at will.

Maybe this is a feature request, and not a bug.

**Comment by stevenguh** [comment]
`bindings` is used to define the whole menu and `bindingOverrides` is designed to surgically update a few bindings (that's why it has `keys`). I agree that it could be better/seamless. Any idea?

**Comment by TwoClocks** [comment]
So, my two cents:
Change all the docs to change any reference to 'keys' to 'key'
Change the code that parses the `BindingOverrides` to look for either 'key' or 'keys' (stay backwards compatible)

Having never looked at the code, maybe now you can use the same parsing code for both?

**Comment by stevenguh** [comment]
Thanks for the suggestions. There some nuances for the overrides. In hinge sight, it is poorly defined API. Supporting both `key` and `keys` may help in this case. I feel like the whole overrides may need to overhaul.

**Comment by jlumpe** [comment]
I'm also confused about `"key"` vs `"keys"`. I was testing the following config:

```json
"whichkey.bindingOverrides": [
    {
        "keys": "x",
        "name": "Test",
        "type": "command",
        "command": "workbench.action.quickOpen",
    },
    {
        "keys": "J",
        "type": "bindings",
        "name": "Jupyter notebook",
        "bindings": [
            {
                "key": "r",
                "name": "Restart kernel",
                "type": "command",
                "command": "jupyter.restartkernel"
            },
            {
                "key": "f",
                "name": "Go to file",
                "type": "command",
                "command": "workbench.action.quickOpen"
            }
        ]
    }
],
```

Here, if I change "keys" to "key" at the top level the bindings do not show up. But if I change "key" to "keys" in the nested items, I get an error:

```
2026-02-17 15:55:43.726 [error] TypeError: Cannot read properties of undefined (reading 'length')
	at c:\Users\jared.lumpe\.cursor\extensions\vspacecode.whichkey-0.11.4-universal\dist\extension-node.js:1:17505
	at Array.reduce (<anonymous>)
	at m.handleRender (c:\Users\jared.lumpe\.cursor\extensions\vspacecode.whichkey-0.11.4-universal\dist\extension-node.js:1:17482)
	at Timeout._onTimeout (c:\Users\jared.lumpe\.cursor\extensions\vspacecode.whichkey-0.11.4-universal\dist\extension-node.js:1:9397)
	at listOnTimeout (node:internal/timers:588:17)
	at process.processTimers (node:internal/timers:523:7)
```

(I'm running in Cursor, which may change things).
